#ifndef __JSON2MAP_CONFIG_H__
#define __JSON2MAP_CONFIG_H__

#define JSON2MAP_MAP_OBJECT_SEPARATOR '.'
#define JSON2MAP_MAP_ARRAY_START '['
#define JSON2MAP_MAP_ARRAY_END ']'
#define JSON2MAP_MAP_ARRAY_COUNT 'x'
#define JSON2MAP_MAP_OBJECT_CODE 'o'

#define JSON2MAP_PRIMITIVE_PREFIXER 27

#endif
