set(SOURCES_APPLICATION
        src/application/application.h
        src/application/config/config.c
        src/application/config/config.h
        src/application/config/configmenu.c
        src/application/config/configmenu.h
        src/application/config/configstates.c
        src/application/config/configstates.h
        src/application/constants.h
        src/application/database/database.c
        src/application/database/database.h
        src/application/definitions/config.h
        src/application/definitions/controller.h
        src/application/definitions/download.h
        src/application/definitions/enums.h
        src/application/definitions/texture.h
        src/application/definitions/themes.h
        src/application/download/download.c
        src/application/download/download.h
        src/application/download/downloader/downloader.c
        src/application/download/downloader/downloader.h
        src/application/download/downloader/downloadercurl.c
        src/application/download/downloader/downloadercurl.h
        src/application/download/downloader/downloaderinternal.c
        src/application/download/downloader/downloaderinternal.h
        src/application/download/downloadmanager.c
        src/application/download/downloadmanager.h
        src/application/download/downloadpipeline.c
        src/application/download/downloadpipeline.h
        src/application/download/postprocess.c
        src/application/download/postprocess.h
        src/application/enginecache/enginecache.c
        src/application/enginecache/enginecache.h
        src/application/helper/map.c
        src/application/helper/map.h
        src/application/helper/path.c
        src/application/helper/path.h
        src/application/helper/uihelper.c
        src/application/helper/uihelper.h
        src/application/input/input.c
        src/application/input/input.h
        src/application/input/keyboard.c
        src/application/input/keyboard.h
        src/application/list/dblist.c
        src/application/list/dblist.h
        src/application/list/list.c
        src/application/list/list.h
        src/application/modal/modal.c
        src/application/modal/modal.h
        src/application/search/search.c
        src/application/search/search.h
        src/application/state/statehandler.c
        src/application/state/statehandler.h
        src/application/state/statesystem.c
        src/application/state/statesystem.h
        src/application/themes/loading.c
        src/application/themes/loading.h
        src/application/themes/rendering.c
        src/application/themes/rendering.h
        src/application/ui/display.c
        src/application/ui/display.h
        src/application/ui/rendering.c
        src/application/ui/rendering.h
        src/application/ui/uihandler.c
        src/application/ui/uihandler.h
        )
add_executable(romfetcher src/application/application.c ${SOURCES_APPLICATION})